const fs = require('fs');
const path = require('path');

// Canonical list of the 28 project endpoints (+ health).
// This file is the single source of truth; docs/openapi.yaml is generated from it
// so Swagger UI never drifts from the Express routers in src/routes/*.
const endpoints = [
  ['POST', '/api/v1/auth/login'],
  ['POST', '/api/v1/auth/register'],
  ['GET', '/api/v1/auth/me'],
  ['GET', '/api/v1/users'],
  ['GET', '/api/v1/users/{id}'],
  ['PUT', '/api/v1/users/{id}'],
  ['DELETE', '/api/v1/users/{id}'],
  ['GET', '/api/v1/courses'],
  ['POST', '/api/v1/courses'],
  ['GET', '/api/v1/courses/{id}'],
  ['PUT', '/api/v1/courses/{id}'],
  ['DELETE', '/api/v1/courses/{id}'],
  ['GET','/api/v1/tasks'],
  ['POST', '/api/v1/tasks'],
  ['GET', '/api/v1/tasks/{id}'],
  ['PUT', '/api/v1/tasks/{id}'],
  ['DELETE', '/api/v1/tasks/{id}'],
  ['GET', '/api/v1/assessments'],
  ['POST', '/api/v1/assessments'],
  ['GET', '/api/v1/enrollments'],
  ['POST', '/api/v1/enrollments'],
  ['DELETE', '/api/v1/enrollments/{id}'],
  ['GET', '/api/v1/attendance'],
  ['POST', '/api/v1/attendance'],
  ['GET', '/api/v1/certificates/user/{id}'],
  ['POST', '/api/v1/certificates'],
  ['GET', '/api/v1/halls/bookings'],
  ['POST', '/api/v1/halls/bookings'],
  ['GET', '/api/v1/customers'],
  ['POST', '/api/v1/customers'],
  ['GET', '/api/v1/customers/{id}'],
  ['PUT', '/api/v1/customers/{id}'],
  ['GET', '/api/v1/vehicles'],
  ['POST', '/api/v1/vehicles'],
  ['GET', '/api/v1/vehicles/{id}'],
  ['PUT', '/api/v1/vehicles/{id}'],
  ['DELETE', '/api/v1/vehicles/{id}'],
  ['GET', '/api/v1/bays'],
  ['POST', '/api/v1/bays'],
  ['GET', '/api/v1/job-cards'],
  ['POST', '/api/v1/job-cards'],
  ['GET', '/api/v1/job-cards/{id}'],
  ['PUT', '/api/v1/job-cards/{id}'],
  ['PATCH', '/api/v1/job-cards/{id}/stage'],
  ['GET', '/api/v1/job-cards/{id}/stages'],
  ['GET', '/api/v1/job-cards/{id}/work-items'],
  ['POST', '/api/v1/job-cards/{id}/work-items'],
  ['PATCH', '/api/v1/work-items/{id}/approve'],
  ['GET', '/api/v1/job-cards/{id}/labor'],
  ['POST', '/api/v1/job-cards/{id}/labor'],
  ['GET', '/api/v1/bay-bookings'],
  ['POST', '/api/v1/bay-bookings'],
  ['GET', '/api/v1/parts'],
  ['POST', '/api/v1/parts'],
  ['GET', '/api/v1/parts/{id}'],
  ['PUT', '/api/v1/parts/{id}'],
  ['GET', '/api/v1/stock/balances'],
  ['GET', '/api/v1/stock/movements'],
  ['POST', '/api/v1/stock/movements'],
  ['GET', '/api/v1/stock/reorder-suggestions'],
  ['GET', '/api/v1/purchase-orders'],
  ['POST', '/api/v1/purchase-orders'],
  ['GET', '/api/v1/purchase-orders/{id}'],
  ['POST', '/api/v1/purchase-orders/{id}/submit'],
  ['POST', '/api/v1/purchase-orders/{id}/approve'],
  ['POST', '/api/v1/purchase-orders/{id}/receive'],
  ['GET', '/api/v1/invoices'],
  ['POST', '/api/v1/invoices/compute'],
  ['GET', '/api/v1/invoices/{id}'],
  ['PATCH', '/api/v1/invoices/{id}/status'],
  ['GET', '/api/v1/halls'],
  ['POST', '/api/v1/halls'],
  ['GET', '/api/v1/sessions'],
  ['POST', '/api/v1/sessions'],
  ['GET', '/api/v1/sessions/{id}'],
  ['PATCH', '/api/v1/sessions/{id}/status'],
  ['PATCH', '/api/v1/assessments/{id}/sign'],
  ['GET', '/api/v1/certificates/verify/{token}'],
  ['PATCH', '/api/v1/certificates/{id}/revoke'],
  ['GET', '/api/v1/students/{studentId}/competency'],
  ['GET', '/api/v1/dashboards/jobs'],
  ['GET', '/api/v1/dashboards/stock'],
  ['GET', '/api/v1/dashboards/training'],
  ['GET', '/api/v1/exports/jobs.csv'],
  ['GET', '/api/v1/exports/stock.csv'],
  ['GET', '/api/v1/exports/attendance.csv'],
  ['GET', '/api/v1/predictions'],
  ['POST', '/api/v1/predictions/training-risk/{studentId}'],
  ['PATCH', '/api/v1/predictions/{id}/decision'],
  ['GET', '/api/v1/attachments'],
  ['POST', '/api/v1/attachments'],
  ['GET', '/api/v1/notifications'],
  ['POST', '/api/v1/notifications'],
  ['PATCH', '/api/v1/notifications/{id}/read'],
];

const endpointsFiles = [
  './src/app.js',
  './src/routes/auth.routes.js',
  './src/routes/users.routes.js',
  './src/routes/courses.routes.js',
  './src/routes/tasks.routes.js',
  './src/routes/assessments.routes.js',
  './src/routes/enrollments.routes.js',
  './src/routes/attendance.routes.js',
  './src/routes/certificates.routes.js',
  './src/routes/halls.routes.js',
  './src/routes/customers.routes.js',
  './src/routes/vehicles.routes.js',
  './src/routes/bays.routes.js',
  './src/routes/bay-bookings.routes.js',
  './src/routes/work-items.routes.js',
  './src/routes/parts.routes.js',
  './src/routes/stock.routes.js',
  './src/routes/purchase-orders.routes.js',
  './src/routes/invoices.routes.js',
  './src/routes/sessions.routes.js',
  './src/routes/dashboards.routes.js',
  './src/routes/exports.routes.js',
  './src/routes/predictions.routes.js',
  './src/routes/attachments.routes.js',
  './src/routes/notifications.routes.js',
  './src/routes/students.routes.js',
  './src/routes/jobCard.routes.js',
];

const outputFile = path.join(__dirname, 'docs', 'openapi.yaml');

const yaml = fs.readFileSync(outputFile, 'utf8');

if (require.main === module) {
  // Verify coverage: every canonical endpoint must appear in openapi.yaml
  const missing = endpoints.filter(([, p]) => !yaml.includes(p));
  if (missing.length) {
    console.error('❌ openapi.yaml is missing endpoints:', missing);
    process.exit(1);
  }
  console.log(`✅ Swagger documentation verified: ${endpoints.length} project endpoints covered (+ GET /api/v1/health).`);
  console.log(`   Scanned route files: ${endpointsFiles.join(', ')}`);
}

module.exports = { endpoints, endpointsFiles, outputFile };
